// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVptAlA3fjF-BcfXwEriagGZXyTZSa2jE',
    appId: '1:1035167177770:web:64abfc979f4af05bf23753',
    messagingSenderId: '1035167177770',
    projectId: 'mdraw-c35e9',
    authDomain: 'mdraw-c35e9.firebaseapp.com',
    storageBucket: 'mdraw-c35e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7KFiJ1tOx8d9vFzL2Mb8pjhVUJjqYq4c',
    appId: '1:1035167177770:android:75a9791fe23eb3a9f23753',
    messagingSenderId: '1035167177770',
    projectId: 'mdraw-c35e9',
    storageBucket: 'mdraw-c35e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABKaBzmh1orPb8TBIrw9YMOZ-Wv3Ilvxc',
    appId: '1:1035167177770:ios:39bbcc86a9cb0743f23753',
    messagingSenderId: '1035167177770',
    projectId: 'mdraw-c35e9',
    storageBucket: 'mdraw-c35e9.appspot.com',
    iosBundleId: 'com.example.custompainterDrawingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABKaBzmh1orPb8TBIrw9YMOZ-Wv3Ilvxc',
    appId: '1:1035167177770:ios:1a0b2d0aab995920f23753',
    messagingSenderId: '1035167177770',
    projectId: 'mdraw-c35e9',
    storageBucket: 'mdraw-c35e9.appspot.com',
    iosBundleId: 'com.example.custompainterDrawingApp.RunnerTests',
  );
}
